### ISSUE TITLE
Issue installing Heatmap (latest version with tooltips)

### ISSUE THREAD

**Issue by vineetgoel** [stormpython/heatmap#42]
Hi,

I tried to uninstall and install the heatmap plugin today, after the tooltips support was added. I am running into the following error while installing the heatmap plugin using the command on the readme:

```
./kibana plugin -i heatmap -u https://github.com/stormpython/heatmap/archive/master.zip
Installing heatmap
Attempting to transfer from https://github.com/stormpython/heatmap/archive/master.zip
Transferring 1811158 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    WARNING in ../src/ui/public/vis/schemas.js
    There is another module with an equal name when case is ignored.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Rename module if multiple modules are expected or use equal casing if one module is expected.

    WARNING in ../src/ui/public/Vis/Schemas.js
    There is another module with an equal name when case is ignored.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Rename module if multiple modules are expected or use equal casing if one module is expected.

    ERROR in ../installedPlugins/heatmap/public/heatmap.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/vineet/kibana-4.5.1-darwin-x64/src/ui/public/template_vis_type/template_vis_type in /Users/vineet/kibana-4.5.1-darwin-x64/installedPlugins/heatmap/public
     @ ../installedPlugins/heatmap/public/heatmap.js 11:32-81

    ERROR in ../installedPlugins/heatmap/public/heatmap_tooltip.css
    Module build failed: ModuleBuildError: Module build failed: CssSyntaxError: /Users/vineet/kibana-4.5.1-darwin-x64/installedPlugins/heatmap/public/heatmap_tooltip.css:4:3: Unknown word
      width: auto;
      fadeout(@gray-darker, 7%);
      ^
      gray-darker: #222222;
        at Input.error (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/css-loader/node_modules/postcss/lib/input.js:65:21)
        at Parser.word (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/css-loader/node_modules/postcss/lib/parser.js:184:30)
        at Parser.loop (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/css-loader/node_modules/postcss/lib/parser.js:61:26)
        at Object.parse [as default] (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/css-loader/node_modules/postcss/lib/parse.js:21:12)
        at new LazyResult (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:54:42)
        at Processor.process (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/css-loader/node_modules/postcss/lib/processor.js:30:16)
        at processCss (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/css-loader/lib/processCss.js:169:24)
        at Object.module.exports (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/css-loader/lib/loader.js:21:15)
        at DependenciesBlock.onModuleBuildFailed (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
        at nextLoader (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
        at /Users/vineet/kibana-4.5.1-darwin-x64/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
        at runSyncOrAsync (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
        at nextLoader (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
        at /Users/vineet/kibana-4.5.1-darwin-x64/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
        at Storage.finished (/Users/vineet/kibana-4.5.1-darwin-x64/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
        at /Users/vineet/kibana-4.5.1-darwin-x64/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
     @ ../installedPlugins/heatmap/public/heatmap.js 4:0-46
```

**Comment by JarenGlover** [comment]
+1

**Comment by arpanshah29** [comment]
+1

**Comment by stormpython** [comment]
The above commit should fix this issue. If not, please re-open the issue.

**Comment by vineetgoel** [comment]
I still keep getting this error:

```
./kibana plugin -i heatmap -u https://github.com/stormpython/heatmap/archive/master.zip
Installing heatmap
Attempting to transfer from https://github.com/stormpython/heatmap/archive/master.zip
Transferring 1811145 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    WARNING in ../src/ui/public/vis/schemas.js
    There is another module with an equal name when case is ignored.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Rename module if multiple modules are expected or use equal casing if one module is expected.

    WARNING in ../src/ui/public/Vis/Schemas.js
    There is another module with an equal name when case is ignored.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Rename module if multiple modules are expected or use equal casing if one module is expected.

    ERROR in ../installedPlugins/heatmap/public/heatmap.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/vineet/kibana-4.5.1-darwin-x64/src/ui/public/template_vis_type/template_vis_type in /Users/vineet/kibana-4.5.1-darwin-x64/installedPlugins/heatmap/public
     @ ../installedPlugins/heatmap/public/heatmap.js 11:32-81
```

Not sure if they are linked.

EDIT: Opening as separate issue
